CFLAGS=-Wall -g
#CFLAGS means rules to compile C | -Wall and -g are flags (options) we are activating
CC = gcc #We are changing the compilator name

clean: #A command with a set of instructions
	rm -f Variables_and_types